### ISSUE TITLE
LIGHT full redeploy checklist

### ISSUE THREAD

**Issue by JackUrb** [facebookresearch/LIGHT#296]
# LIGHT Redeploy Checklist
**Minimum Proof of Concept**
- [x] build the new databases, such that they can be deployed on AWS
- [x] #297 (Update the main server to write to the `EpisodeDB`)
- [x] #298 (update main server to read from the `UserDB`)
- [x] #300 (Finish `ModelPool` abstraction to consolidate model initialization)
- [x] #302 (Make it possible to connect to hosted models).
- [x] Deploy new DBs to AWS
- [x] Deploy model servers
- [x] Create dummy `WorldServer` that wraps existing deploy. Deploy as a single instance.
- [x] Test end-to-end LIGHT with single world server and multiple model servers

**Complete Deploy**
- [ ] Create `LandingServer` - split authentication out from `WorldServer`
- [ ] Create server registry DB
- [ ] Move static files out from deploy servers to scaling bucket
- [ ] Extend `WorldServer`
  - [ ] Add functionality to self-register to the registry
  - [ ] Add functionality to remove from registry on graceful shutdown
  - [ ] Launch second world server, test e2e quick deploys
- [ ] update all the routing to point to the `LandingServer`

**Add world builder**
- [ ] Update the graph builders to point to the new `EnvDB` 
- [ ] Port the `LIGHTDatabase` out and over
- [ ] Revamp world builder backend to map to `EnvDB` for loading components and saving graphs
- [ ] Point the world builder to the model servers as well (maybe handled on the `LandingServer`?)
